### ISSUE TITLE
Error when silent opening chest

### ISSUE THREAD

**Issue by dwilley83** [MyzelYam/SuperVanish#13]
Console shows an error when a vanished player opens a chest.

`[13:23:16] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to SuperVanish v5.9.4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:647) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:88) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at de.myzelyam.supervanish.visibility.SilentChestListeners_v3.restoreState(SilentChestListeners_v3.java:163) ~[?:?]
	at de.myzelyam.supervanish.visibility.SilentChestListeners_v3.onMove(SilentChestListeners_v3.java:91) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-cd6ba67-a7d074c]`

After the chest "closes" the vanished player will drop down a 1 block into the floor. This does not happen if you're looking into the enderchest.

**Comment by npritzer** [comment]
I saw this on one of RGA Gaming's videos.

**Comment by MyzelYam** [comment]
Will be fixed soon, installing ProtocolLib should solve the issue temporarily

**Comment by MyzelYam** [comment]
Fixed
