### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by EvilOlaf** [MyzelYam/SuperVanish#16]
```
[16:41:41 WARN]: org.apache.commons.lang.UnhandledException: Plugin SuperVanish v5.9.5 generated an exception while executing task 57
>       at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
>       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>       at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player$Spigot.sendMessage(Lnet/md_5/bungee/api/ChatMessageType;[Lnet/md_5/bungee/api/chat/BaseComponent;)V
>       at de.myzelyam.supervanish.visibility.ActionBarMgr$1.run(ActionBarMgr.java:39)
>       at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
>       at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
>       ... 3 more
```
This message gets repeatedly spammed to console.
Disabling `DisplayActionBarsToInvisiblePlayers:` solves this issue.

SV5.9.5 
Spigot1.8.8

I know you prefer private messages in Spigot forums.... well... my place is here for some reason :D. I  hope you will read it anyways.

Thanks for that.

Best regards
Olaf

**Comment by SimonOrJ** [comment]
looks like you need to use older version of SV that supports Spigot 1.8...

**Comment by MyzelYam** [comment]
Fixed in latest
