### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by HyperBlueCore** [MyzelYam/SuperVanish#17]
Whenever im in vanish i get this error 
[18:08:21 WARN]: [SuperVanish] Plugin SuperVanish v5.9.7 generated an exception while executing task 79
java.lang.NoSuchMethodError: org.bukkit.entity.Player.spigot()Lorg/bukkit/entity/Player$Spigot;
        at de.myzelyam.supervanish.visibility.ActionBarMgr$1.run(ActionBarMgr.java:42) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[spigot.jar:git-Bukkit-11323bf]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Bukkit-11323bf]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by SimonOrJ** [comment]
That version of SuperVanish is compatible with only 1.12 due to the usage of `Player.spigot()` method.  You need to use older version of it.
