### ISSUE TITLE
NoClassDefFound Error in spigot 1.8

### ISSUE THREAD

**Issue by MrRiptide** [MyzelYam/SuperVanish#22]
` [SuperVanish] Unhandled exception number 1024 occured in onPacketSending(PacketEvent) for SuperVanish
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedServerPing
        at com.comphenix.protocol.wrappers.BukkitConverters$15.getSpecificValue(BukkitConverters.java:742) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.wrappers.BukkitConverters$15.getSpecificValue(BukkitConverters.java:734) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:142) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:230) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:198) ~[ProtocolLib.jar:4.3.0]
        at de.myzelyam.supervanish.visibility.ServerListPacketListener.onPacketSending(ServerListPacketListener.java:51) ~[SuperVanish.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:440) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.encode(ChannelInjector.java:247) [ProtocolLib.jar:4.3.0]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:111) [spigot.jar:git-Spigot-550ebace-7019900e]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.write(ChannelInjector.java:253) [ProtocolLib.jar:4.3.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:657) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:715) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:650) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:657) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:715) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:705) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:740) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:241) [spigot.jar:git-Spigot-550ebace-7019900e]
        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) [ProtocolLib.jar:4.3.0]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:132) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:101) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.PacketStatusListener.a(PacketStatusListener.java:131) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.PacketStatusInStart.a(SourceFile:23) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.PacketStatusInStart.a(SourceFile:8) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:84) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.NetworkManager.channelRead0(NetworkManager.java:249) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-550ebace-7019900e]
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib.jar:4.3.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.LegacyPingHandler.channelRead(SourceFile:94) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) [spigot.jar:git-Spigot-550ebace-7019900e]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-550ebace-7019900e]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
`

I am using the latest version of SuperVanish and of ProtocolLib
I am using spigot version 1.8-R0.1-SNAPSHOT

**Comment by MyzelYam** [comment]
You are using an outdated version of 1.8 spigot, please use the latest 1.8 build or a newer version of minecraft
