### ISSUE TITLE
SV Error On Console

### ISSUE THREAD

**Issue by DiamondDaniel** [MyzelYam/SuperVanish#41]
The Error Message on console

16.01 18:20:58 [Server] WARN [SuperVanish] Task #72 for SuperVanish v6.0.4 generated an exception
16.01 18:20:58 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedChatComponent
16.01 18:20:58 [Server] INFO at de.myzelyam.supervanish.visibility.ActionBarMgr.sendActionBar(ActionBarMgr.java:60) ~[?:?]
16.01 18:20:58 [Server] INFO at de.myzelyam.supervanish.visibility.ActionBarMgr.access$200(ActionBarMgr.java:30) ~[?:?]
16.01 18:20:58 [Server] INFO at de.myzelyam.supervanish.visibility.ActionBarMgr$1.run(ActionBarMgr.java:47) ~[?:?]
16.01 18:20:58 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
16.01 18:20:58 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
16.01 18:20:58 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
16.01 18:20:58 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
16.01 18:20:58 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
16.01 18:20:58 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
16.01 18:20:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by DiamondDaniel** [comment]
I am using the latest version of SuperVanish and ProtocolLib

**Comment by DiamondDaniel** [comment]
Fixed!
