### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by redfox80** [MyzelYam/SuperVanish#45]
Everytime I vanish i get this in the console. Not completely certain what it means but it's flooding the console making it hard to find usefull information there.

Also i no longer get the 'you are invisible' text while vanished

10.06 11:16:57 [Server] Server thread/ERROR Could not pass event PlayerHideEvent to SuperVanish v6.1.1
10.06 11:16:57 [Server] INFO org.bukkit.event.EventException: null
10.06 11:16:57 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:68) ~[?:?]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:43) ~[?:?]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.commands.SubCommand.hidePlayer(SubCommand.java:36) ~[?:?]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.commands.subcommands.VanishSelf.execute(VanishSelf.java:33) ~[?:?]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.commands.SubCommandMgr.execute(SubCommandMgr.java:50) ~[?:?]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.commands.VanishCommand.execute(VanishCommand.java:29) ~[?:?]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.SuperVanish.onCommand(SuperVanish.java:171) ~[?:?]
10.06 11:16:57 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
10.06 11:16:57 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.features.NightVision.sendAddPotionEffect(NightVision.java:107) ~[?:?]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.features.NightVision.onVanish(NightVision.java:53) ~[?:?]
10.06 11:16:57 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
10.06 11:16:57 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
10.06 11:16:57 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
10.06 11:16:57 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
10.06 11:16:57 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO ... 28 more
10.06 11:16:57 [Server] Server thread/WARN [SuperVanish] Task #5236 for SuperVanish v6.1.1 generated an exception
10.06 11:16:57 [Server] INFO java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.features.NightVision.sendRemovePotionEffect(NightVision.java:132) ~[?:?]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.features.NightVision.run(NightVision.java:87) ~[?:?]
10.06 11:16:57 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
10.06 11:16:57 [Server] Server thread/WARN [SuperVanish] Task #5234 for SuperVanish v6.1.1 generated an exception
10.06 11:16:57 [Server] INFO java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
10.06 11:16:57 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.visibility.ActionBarMgr.sendActionBar(ActionBarMgr.java:73) ~[?:?]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.visibility.ActionBarMgr.access$200(ActionBarMgr.java:30) ~[?:?]
10.06 11:16:57 [Server] INFO at de.myzelyam.supervanish.visibility.ActionBarMgr$1.run(ActionBarMgr.java:47) ~[?:?]
10.06 11:16:57 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar:git-Spigot-df0eb25-0309d17]
10.06 11:16:57 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by htAngryFace** [comment]
Same issue and warning.

**Spigot Version:**
CraftBukkit version git-Spigot-c8d4cef-1fee35b (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

**SuperVanish version:**
6.1.2

**Other Plugins:**
ActionHealth, AdvancedAchievements, AdvancedAchievements-LuckPerms-Hook, ChestSort, ClearLag, CoreProtect, Dispensator, DynamicShop, EditableSign, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, GSit, Jobs, LuckPerms, Minepacks, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, PlaceholderAPI, PlugMan, ProtocolLib, Residence, Vault, WorldBorder, WorldEdit, WorldGuard

---

**Error**:
```
[00:49:05] [Server thread/ERROR]: Could not pass event PlayerHideEvent to SuperVanish v6.1.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at de.myzelyam.supervanish.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:68) ~[?:?]
        at de.myzelyam.supervanish.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:43) ~[?:?]
        at de.myzelyam.supervanish.commands.SubCommand.hidePlayer(SubCommand.java:36) ~[?:?]
        at de.myzelyam.supervanish.commands.subcommands.VanishSelf.execute(VanishSelf.java:33) ~[?:?]
        at de.myzelyam.supervanish.commands.SubCommandMgr.execute(SubCommandMgr.java:50) ~[?:?]
        at de.myzelyam.supervanish.commands.VanishCommand.execute(VanishCommand.java:29) ~[?:?]
        at de.myzelyam.supervanish.SuperVanish.onCommand(SuperVanish.java:172) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
        at de.myzelyam.supervanish.features.NightVision.sendAddPotionEffect(NightVision.java:107) ~[?:?]
        at de.myzelyam.supervanish.features.NightVision.onVanish(NightVision.java:53) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        ... 28 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.Validate
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
        at de.myzelyam.supervanish.features.NightVision.sendAddPotionEffect(NightVision.java:107) ~[?:?]
        at de.myzelyam.supervanish.features.NightVision.onVanish(NightVision.java:53) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        ... 28 more
[00:49:06] [Server thread/WARN]: [SuperVanish] Task #45 for SuperVanish v6.1.2 generated an exception
java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
        at de.myzelyam.supervanish.visibility.ActionBarMgr.sendActionBar(ActionBarMgr.java:73) ~[?:?]
        at de.myzelyam.supervanish.visibility.ActionBarMgr.access$200(ActionBarMgr.java:30) ~[?:?]
        at de.myzelyam.supervanish.visibility.ActionBarMgr$1.run(ActionBarMgr.java:47) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[00:49:07] [Server thread/INFO]: htAngryFace issued server command: /sv
[00:49:07] [Server thread/ERROR]: Could not pass event PlayerShowEvent to SuperVanish v6.1.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at de.myzelyam.supervanish.visibility.VisibilityChanger.showPlayer(VisibilityChanger.java:119) ~[?:?]
        at de.myzelyam.supervanish.visibility.VisibilityChanger.showPlayer(VisibilityChanger.java:47) ~[?:?]
        at de.myzelyam.supervanish.commands.SubCommand.showPlayer(SubCommand.java:40) ~[?:?]
        at de.myzelyam.supervanish.commands.subcommands.VanishSelf.execute(VanishSelf.java:31) ~[?:?]
        at de.myzelyam.supervanish.commands.SubCommandMgr.execute(SubCommandMgr.java:50) ~[?:?]
        at de.myzelyam.supervanish.commands.VanishCommand.execute(VanishCommand.java:29) ~[?:?]
        at de.myzelyam.supervanish.SuperVanish.onCommand(SuperVanish.java:172) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
        at de.myzelyam.supervanish.features.NightVision.sendRemovePotionEffect(NightVision.java:132) ~[?:?]
        at de.myzelyam.supervanish.features.NightVision.onReappear(NightVision.java:60) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
        ... 28 more
```
